minimumReleaseAge: 1440

packages:
  - artifacts/*
  - lib/*
  - scripts

catalog:
  '@tanstack/react-query': ^5.90.21
  '@types/node': ^25.3.3
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  drizzle-orm: ^0.45.2
  react: 19.1.0
  react-dom: 19.1.0
  tsx: ^4.21.0
  vite: ^7.3.2
  zod: ^3.25.76

autoInstallPeers: false
